# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

In [14]:
from typing import List
import re

def tokenize_words(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    return re.findall(r"[a-zA-Z0-9']+", text)

def tokenize_sentence(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing sentences tokenized from text

    """
    
    return re.split(r'(?<=[.!?])(?=\s*[A-Z0-9])', text)

text = "Here we go again. I was supposed to add this text later.\
Well, it's 10.p.m. here, and I'm actually having fun making this course. :o\
I hope you are getting along fine with this presentation, I really did try.\
And one last sentence, just so you can test you tokenizers better."

print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))

Tokenized sentences:
['Here we go again.', ' I was supposed to add this text later.', "Well, it's 10.p.m. here, and I'm actually having fun making this course. :oI hope you are getting along fine with this presentation, I really did try.", 'And one last sentence, just so you can test you tokenizers better.']
Tokenized words:
['Here', 'we', 'go', 'again', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later', 'Well', "it's", '10', 'p', 'm', 'here', 'and', "I'm", 'actually', 'having', 'fun', 'making', 'this', 'course', 'oI', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation', 'I', 'really', 'did', 'try', 'And', 'one', 'last', 'sentence', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better']


## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

In [8]:
import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
file = open("../datasets/trump.txt", "r",encoding="utf-8") 
trump = file.read()
words = tokenize_words(trump)
tags = nltk.pos_tag(words)
tags[:10]

# fill the gap and imports

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/kprzystalski/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/kprzystalski/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


[('Thank', 'NNP'),
 ('you', 'PRP'),
 ('very', 'RB'),
 ('much', 'JJ'),
 ('Mr', 'NNP'),
 ('Speaker', 'NNP'),
 ('Mr', 'NNP'),
 ('Vice', 'NNP'),
 ('President', 'NNP'),
 ('Members', 'NNP')]

## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [23]:
import spacy

file = open("../datasets/trump.txt", "r",encoding='utf-8') 
trump = file.read() 

### here comes your code
nlp = spacy.load("en_core_web_sm")
document = nlp(trump)
sentences = list(document.sents)[-10:]
for sentence in sentences:
    print(sentence)
    print([word.text for word in sentence if word.pos_=="NOUN"],end="\n\n")


When we fulfill this vision, when we celebrate our 250 years of glorious freedom, we will look back on tonight as when this new chapter of American greatness began.
['vision', 'years', 'freedom', 'tonight', 'chapter', 'greatness']

The time for small thinking is over.
['time', 'thinking']

The time for trivial fights is behind us.
['time', 'fights']

We just need the courage to share the dreams that fill our hearts, the bravery to express the hopes that stir our souls, and the confidence to turn those hopes and those dreams into action.


['courage', 'dreams', 'hearts', 'bravery', 'hopes', 'souls', 'confidence', 'hopes', 'dreams', 'action']

From now on, America will be empowered by our aspirations, not burdened by our fears; inspired by the future, not bound by failures of the past; and guided by our vision, not blinded by our doubts.


['aspirations', 'fears', 'future', 'failures', 'past', 'vision', 'doubts']

I am asking all citizens to embrace this renewal of the American spirit.
[

## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [19]:
import numpy as np
import spacy

class BagOfWords:
    """Basic BoW implementation."""
    
    __nlp = spacy.load("en_core_web_sm")
    __bow_list = []
    
    # your code goes maybe also here    
    
    def fit_transform(self, corpus: list):
        """Transform list of strings into BoW array.

        Parameters
        ----------
        corpus: List[str]
                Corpus of texts to be transforrmed

        Returns
        -------
        np.array
                Matrix representation of BoW

        """
        self.__bow_list = sorted(list(set(word.lower() for doc in corpus for word in tokenize_words(doc))))
        bow_matrix = np.zeros((len(corpus),len(self.__bow_list)), dtype=int)
        for i, doc in enumerate(corpus):
            for word in tokenize_words(doc):
                word_index = self.__bow_list.index(word.lower())
                bow_matrix[i, word_index] += 1
        return bow_matrix
      

    def get_feature_names(self) -> list:
        """Return words corresponding to columns of matrix.

        Returns
        -------
        List[str]
                Words being transformed by fit function

        """   
        # your code goes here
        return self.__bow_list

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]    
    
vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

print(vectorizer.get_feature_names())
len(vectorizer.get_feature_names())

[[0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1]
 [1 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 2 1 0 0 1 0 1 0 0]]
['a', 'as', 'bag', 'based', 'below', 'can', 'counting', 'document', 'documents', 'gives', 'is', 'matrix', 'most', 'multiple', 'occur', 'occurences', 'of', 'on', 'once', 'only', 'pretty', 'really', 'see', 'sparse', 'the', 'third', 'this', 'throughout', 'us', 'words', 'you']


31

## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [39]:
from nltk.book import *

wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1;

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    # print(counts.keys())
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

In [46]:
def clean_generated(text):
    # put your code here
    end_marks = {'.','?','!',''}
    output = ""
    prev_word = ""
    for word in text.split():
        if prev_word in end_marks:
            output += word.capitalize()
        elif word in end_marks:
            output = output.rstrip()
            output += word
        else:
            output += word
        output += " "
        prev_word = word
    return output

N=3 # fix it for other value of N

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq="engineering industry"

counts = ngram_freqs(ngrams)

if start_seq is None: start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower();

sentences = 0
while sentences < sentence_count:
    generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.','!', '?')) else 0

# put your code here:

print(generated, end="\n\n")
print(clean_generated(generated))


engineering industry . What saved many farmers from a blender to chairs to a record 59.9 billion last year and last month at 47.6 in October from 46 in September . But any potential acquirer must attempt to get the rhythm of the East bloc Nomenklatura and they are awarded . The cash value of their trades that they can not provide information about clients who do n't have the working poor while opponents argued that local councils have refused to take away the right to read Voice of America said 0 manufacturing shrank further in October 1991 unless I get fired . Mr.

Engineering industry. What saved many farmers from a blender to chairs to a record 59.9 billion last year and last month at 47.6 in October from 46 in September. But any potential acquirer must attempt to get the rhythm of the East bloc Nomenklatura and they are awarded. The cash value of their trades that they can not provide information about clients who do n't have the working poor while opponents argued that local counc